### ISSUE TITLE
why use injectGlobal and remcalc?

### ISSUE THREAD

**Issue by tsiq-swyx** [SaraVieira/awesome-talks#26]
Hi Sara! just trying to learn from your code!

I notice in https://github.com/SaraVieira/awesome-talks/blob/master/src/Utils/global-styles.js you use `injectGlobal` from styled-components, together with `remcalc`.

I do use css-in-js but normally here i'd just have a `global.css` and import it, and just use rem's everywhere.

I'm not disagreeing with you here, just thought it was an interesting technical choice, and maybe something I can learn from. Wonder if you could talk a little about why you use `injectGlobal` + `remcalc` instead of other maybe more common approaches? thanks very much!

**Comment by SaraVieira** [comment]
Hey !

> Hi Sara! just trying to learn from your code!

That's your mistake right there 😂

> Wonder if you could talk a little about why you use injectGlobal + remcalc instead of other maybe more common approaches? 

I don't have a specific reason but some reasons why I started coding this way with styled components.
* First I don't know how to css with nesting anymore and adding the inject global allows me to do nesting while a normal css file would not.
* Then I also think it's helpful the fact that I can still use the theme colors in there so if I change that color it will reflect everywhere and if I used a CSS file that would not be the case.
* Inject global then also allows me to use it in other places I need some global styles like in here for the modal:https://github.com/SaraVieira/awesome-talks/blob/master/src/Components/Nav.js#L63 and this way I can keep the whole thing consistent.
* About remcalc that is just because I find it very hard to see calc and convert it back to px and since the lib is just 1kb I find it really helps me make sense of the code.

It may look a little weird and overly complicated at first glance I'll give you that ahah

All of that said this my way of coding and like anything it's subjective but I hope that makes sense to you 😄

**Comment by tsiq-swyx** [comment]
interesting. thank you very much! yea i know css in js is a very very unsolved problem so i'm always on the look out for how other people do it. i'm sure what i do (pure css + style tag 90% of the time, then styled-components) can't really be the "best" way.
